version: '3.8'

services:
  postgres:
    image: postgres:11-alpine
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=mmsuser
      - POSTGRES_DB=mms
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    network_mode: host
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

  minio:
    image: minio/minio:latest
    network_mode: host
    environment:
      - "MINIO_ACCESS_KEY=admintest"
      - "MINIO_SECRET_KEY=admintest"
    command: server /tmp/data
    ports:
      - 9000:9000
